
DELETE FROM products_product;

INSERT INTO products_product (name, price, image, description, available, created_at) VALUES
('Wireless Bluetooth Headphones', 59.99, 'products/default.png', 'High‑quality wireless headphones with deep bass and noise cancellation.', true, NOW()),
('Smart Fitness Watch', 129.50, 'products/default.png', 'Track your heart rate, steps and sleep with this sleek fitness watch.', true, NOW()),
('USB‑C Fast Charger', 19.99, 'products/default.png', 'Fast charging USB‑C adapter for phones and tablets.', true, NOW()),
('Portable Power Bank 10000mAh', 24.99, 'products/default.png', 'Reliable power bank to keep your devices charged on the go.', true, NOW()),
('4K Ultra HD Action Camera', 89.00, 'products/default.png', 'Waterproof action camera with wide‑angle lens and accessories.', true, NOW()),
('Wireless Ergonomic Mouse', 29.99, 'products/default.png', 'Comfortable wireless mouse with adjustable DPI.', true, NOW()),
('Gaming Keyboard RGB', 49.95, 'products/default.png', 'Mechanical keyboard with customizable RGB lighting.', true, NOW()),
('Laptop Backpack 15.6"', 39.99, 'products/default.png', 'Durable backpack with padded laptop compartment.', true, NOW()),
('Smart LED Desk Lamp', 34.50, 'products/default.png', 'LED desk lamp with brightness and color temperature control.', true, NOW()),
('Portable Bluetooth Speaker', 45.00, 'products/default.png', 'Compact speaker with rich sound and long battery life.', true, NOW()),
('Noise Cancelling Earbuds', 79.99, 'products/default.png', 'True wireless earbuds with active noise cancellation.', true, NOW()),
('HD Webcam 1080p', 39.99, 'products/default.png', 'Crystal‑clear webcam for video conferencing and streaming.', true, NOW()),
('Gaming Headset with Mic', 59.00, 'products/default.png', 'Comfortable headset with high‑quality microphone for gaming.', true, NOW()),
('Smartphone Gimbal Stabilizer', 99.99, 'products/default.png', '3‑axis gimbal stabilizer for smooth video recording.', true, NOW()),
('Wireless Charging Pad', 25.50, 'products/default.png', 'Qi‑certified wireless charger for compatible phones.', true, NOW()),
('Bluetooth Car Adapter', 18.99, 'products/default.png', 'Plug‑in adapter for hands‑free calling and music in car.', true, NOW()),
('4‑Port USB Hub', 22.00, 'products/default.png', 'Expand your ports with a compact USB hub.', true, NOW()),
('Laptop Stand Adjustable', 28.99, 'products/default.png', 'Ergonomic laptop stand for improved posture.', true, NOW()),
('Smart Thermostat', 129.99, 'products/default.png', 'Energy‑saving thermostat with Wi‑Fi control.', true, NOW()),
('Indoor Security Camera', 59.95, 'products/default.png', 'Easy‑install security camera with night vision.', true, NOW()),
('Wireless Game Controller', 49.99, 'products/default.png', 'Compatible controller for PC and consoles.', true, NOW()),
('HDMI Cable 6ft', 11.99, 'products/default.png', 'High‑speed HDMI cable for 4K video.', true, NOW()),
('Bluetooth Tracker Tag', 19.50, 'products/default.png', 'Track your keys and accessories with Bluetooth tag.', true, NOW()),
('Digital Kitchen Scale', 24.00, 'products/default.png', 'Precision kitchen scale for baking and cooking.', true, NOW()),
('Electric Toothbrush Set', 59.99, 'products/default.png', 'Rechargeable toothbrush with multiple brush modes.', true, NOW()),
('Portable Mini Projector', 149.00, 'products/default.png', 'Compact projector for outdoor movie nights.', true, NOW()),
('Adjustable Dumbbells Set', 99.99, 'products/default.png', 'Space‑saving adjustable dumbbell weights.', true, NOW()),
('Yoga Mat with Carry Strap', 29.99, 'products/default.png', 'Comfortable non‑slip yoga mat.', true, NOW()),
('Stainless Steel Water Bottle', 19.99, 'products/default.png', 'Insulated bottle keeps drinks cold or hot.', true, NOW()),
('Air Purifier HEPA', 89.99, 'products/default.png', 'HEPA air purifier for cleaner indoor air.', true, NOW());